version: "3.3"  # optional since v1.27.0
services:
version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
  whitelist:
    links:
      - "cache:cache"
    build: .
    ports:
      - "8000:8000"
    restart: always
volumes:
  cache:
    driver: local
